Json unmarshal errors 68430
programmfabrik/golib pull request #2
Opened 2024-05-23 15:11 UTC by phempel

2024-05-25 05:20 UTC, martinrode requested changes
die änderungen mit den fmt.Errorf sind zwar richtig, aber das wäre für mich ein separater patch. so finde ich es aufwendig den code review zu machen.

2024-05-25 05:20 UTC, martinrode commented on count_writer.go
> +var LimitExceeded = fmt.Errorf("Limit exceeded")
fmt.Errorf nur verwenden, wenn es Argumente hat

2024-05-25 05:20 UTC, martinrode commented on env.go
> +	errNotAddressable = fmt.Errorf("Not addressable")
s.o., errors.New lassen

2024-05-25 05:20 UTC, martinrode commented on errors.go
> +	}
Keine extra struct mit "params". Nur SourceType und TargetType.

2024-05-25 05:20 UTC, martinrode commented on errors.go
> +}
Das ist alles nicht nötig und verwirrt nur wenn du hier die errorgen errors simulierst.

2024-05-25 05:20 UTC, martinrode commented on int.go
> +		return 0, fmt.Errorf("Float has fractional part")
s.o.

2024-05-25 05:20 UTC, martinrode commented on json.go
> +				Value(string(source)).
Value brauchen wir nicht. Es reicht SourceType und TargetType. Alles andere hat der Caller schon

2024-05-25 05:20 UTC, martinrode commented on json_test.go
> +			"obj": {
Du brauchst hier nicht das Json parsing testen. Das hat die Go Stdlib im Griff...

2024-05-25 05:20 UTC, martinrode commented on localization.go
> +				return fmt.Errorf(`Localization.Load: Column "key" found in CSV data.`)
s.o.

2024-05-27 17:54 UTC, martinrode requested changes

2024-05-27 17:54 UTC, martinrode commented on errors.go
> +}
Diese func ist überflüssig.

2024-05-27 17:54 UTC, martinrode commented on errors.go
> +
Die brauchen wir nicht.

2024-05-27 17:54 UTC, martinrode commented on errors.go
> +}
Das brauchen wir nicht. Man will den SourceType doch nicht von "draußen" setzen.

2024-05-27 17:54 UTC, martinrode commented on errors.go
> +}
Hier würde ich das einfach "SourceType" nennen.

2024-05-27 17:54 UTC, martinrode commented on errors.go
> +}
Auch diese func brauchen wir nicht. Und sie heisst auch nicht so wie die andere die wir nicht brauchen ("Set" fehlt).

2024-05-27 17:54 UTC, martinrode commented on errors.go
> +}
Wir brauchen nur TargetType, ohne Get

2024-05-27 17:54 UTC, martinrode commented on errors.go
> +
Brauchen wir auch nicht

2024-05-27 17:54 UTC, martinrode commented on errors.go
> +}
Auch hier ohne Get

2024-05-27 17:54 UTC, martinrode commented on json.go
> +				TargetType(matches[2])
Das hier ist nicht "errorgen". Schau doch nochmal in meine ursprüngliche Skizze dieses "JsonUnmarshalError", da ist im Prinzip alles was wir brauchen.

2024-05-27 17:54 UTC, martinrode commented on errors.go
> +type ErrJsonUnmarshal struct {
Warum nicht "JsonUnmarshalError", so wie vorher finde ich besser.

2024-05-27 17:54 UTC, martinrode commented on json_test.go
> +		expectedTargetPropertyName string
In kurzen funcs braucht man keine langen Variablen-Namen. Gerade in diesem fall heir würde ich mit kürzeren Identifiern arbeiten.

2024-05-28 07:12 UTC, phempel commented on errors.go
> +}
Wo gibt es denn ein "Set"? Diese Funktion hat das selbe Namensschema wie alle anderen

2024-05-28 07:15 UTC, phempel commented on json_test.go
> +		expectedTargetPropertyName string
Das ist das was ich schon so oft in Sprint Meetings etc angesprochen habe, seit wann rechtfertigen Variablennamen Change requests? Das ist doch wirklich nur noch eine Geschmacksfrage, und wenn wir anstatt uns darauf zu konzentrieren dass es überhaupt mal funktioniert, nur noch um Stil diskutieren finde ich das nur Zeitverschwendung. Ich hab auch noch andere Tickets neben fylr... 

Und wenn ich die Variablen umbenennen soll, wie konkret? ich will jetzt nicht raten was der korrekte Name wäre. Außerdem geht es hier nur um einen unittest, das ist nicht mal der tatsächliche Code... Also ich verstehe wirklich nicht warum so etwas ständig kritisiert wird, das ist nicht zielführend.

2024-05-29 12:28 UTC, martinrode requested changes

2024-05-29 12:28 UTC, martinrode commented on json_test.go
> +			property: "JsonValues.obj.array",
Diese vielen Tests sind im Grund nicht so relevant, weil sie ja alle denselben Code Path in der golib und auch im JSON stdlib code testen.

Was wichtiger wäre ist ein Test der die non struct error message (3 value message) testet, das habe ich nicht gesehen. Und das berührt dann wiederum mehr Code.

2024-05-29 12:28 UTC, martinrode commented on errors.go
> +}
Ich würde den original error text einfach so durchreichen. Also `return jue.err.Error()`. Die anderen funcs sind ja dafür da das man die Info geparst rausziehen kann.

2024-05-30 09:10 UTC, closed without merging